version: '3.8'

services:
  java-backend:
    build: ./demo # Points to your Java folder
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env

  ml-service:
    build: ./ml-service # Points to your Python folder
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend # Points to your React folder
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_TARGET=http://java-backend:8080
      - VITE_ML_TARGET=http://ml-service:8000
    depends_on:
      - java-backend
      - ml-service